### ISSUE TITLE
Build seeder

### ISSUE THREAD

**Issue by cjavdev** [cjavdev/uscsa_seeder#44]
This requires some understanding of how that works. Is it random?

**Comment by Dbz** [comment]
For timed events (GS, SL), use the seed order as your start list.
For style events (SLP, HP, QP, JAM), use the seeds in the reverse order as your start list so the worst athletes go first.
For BX events format is 6 racers at a time, Seeding the Highest against the lowest, like March Madness brackets, so we don't have the best guys getting knocked out too early and for our final run looking like a slaughter.

Is this what you were looking for?

**Comment by cjavdev** [comment]
So I think i have this working for BX, and that's how its seeding every event right now. 
In the EventSeedingReport model we can instantiate different types of seeder objects, the current one is based on bx and should be renamed to HighVsLowSeeder or something, the others should be named relative to what they do. SeedOrderSeeder, BestLastSeeder, Then depending on the type of the event, it instantiates and memoizes a local copy of the model's master seeder.
