### ISSUE TITLE
prevent seeding after seed closes at time (5pm day before)

### ISSUE THREAD

**Issue by cjavdev** [cjavdev/uscsa_seeder#50]
we can use Timecop to write some specs for this.

**Comment by cjavdev** [comment]
Also, we should remove the seed button for captains.

**Comment by Dbz** [comment]
Seed button gets removed for captains, and the seed will not save if it is past the deadline. League managers can still change seeds. Right now there is no way for captains to seed after the deadline nor for league managers to allow captains to seed after the deadline

**Comment by Dbz** [comment]
Actually doesn't seed to 100% work. It's the 21st and seeding still appears for the race that is the 21st even though registration closed yesterday
